apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: us-central1-docker.pkg.dev/final-ip/yolo-repo/backend-side:v1.0.0
          ports:
            - containerPort: 5000
          env:
            - name: REACT_APP_MONGODB_URL
              value: "mongodb://mongo-service:27017/yolomy" # Update this to match the MongoDB service and database name

