version: '3'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:80
    volumes:
      - ./client:/app/client
    networks:
      - project-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
      
    volumes:
      - ./backend:/app/backend
    networks:
      - project-network
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - project-network

networks:
  project-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
