apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: us-central1-docker.pkg.dev/final-ip/yolo-repo/client-side:v1.0.0
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              value: "http://backend-service:5000/api/products"
            - name: REACT_APP_MONGODB_URL
              value: "mongodb://mongo-service:27017/yolomy"

