---
- name: Provision MERN application
  hosts: all
  become: true
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Docker dependencies
      apt:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
        state: present
        update_cache: yes
        validate_certs: no

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Docker and Docker Compose
      apt:
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
        state: present

    - name: Add the vagrant user to the docker group
      user:
        name: vagrant
        groups: docker
        append: yes

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Python 3 and pip
      apt:
        name: ['python3', 'python3-pip']
        state: present
        update_cache: yes

    - name: Install Docker Python SDK for Docker Compose
      pip:
        name: docker
        state: present

    - name: Install Docker Compose
      pip:
        name: docker-compose
        state: present

    # Clone your MERN application repository (replace with your actual repository URL)
    - name: Clone MERN application
      git:
        repo: "https://github.com/Ramsey-Gicharu/yolo.git"
        dest: /home/vagrant/mern-app
        clone: yes

    # Run Docker Compose for the MERN application
    - name: Run Docker Compose for MERN application
      command: docker-compose -f /home/vagrant/mern-app/docker-compose.yml up -d
      args:
        creates: /home/vagrant/mern-app
